# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
parameters:
  formula:
    type: string
    default: "zlib"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install ruby"
          command: "sudo snap install ruby --channel=2.6/stable --classic"
      - restore_cache:
          keys: 
            - homebrew-with-taps
            - homebrew-repo
      - run:
          name: "Clone homebrew"
          command: |
            if [ ! -d "homebrew" ] ; then
             git clone https://github.com/Homebrew/brew homebrew
            else
             echo Using cached homebrew
            fi
      - save_cache:
          key: homebrew-repo
          paths:
            - homebrew
      - run:
          name: "Install homebrew"
          command: |
            if [ ! -d "homebrew/Library/Taps" ] ; then
            eval "$(homebrew/bin/brew shellenv)"
            brew update --force --quiet || true
            # chmod -R go-w "$(brew --prefix)/share/zsh"
            else
             echo Using cached homebrew taps
            fi

      - save_cache:
          key: homebrew-with-taps
          paths:
            - homebrew
      - run:
          name: "Install spokeo"
          command: |
            sudo curl -L "https://github.com/whalebrew/whalebrew/releases/latest/download/whalebrew-Linux-arm64" -o /usr/local/bin/whalebrew; sudo chmod +x /usr/local/bin/whalebrew
            /usr/local/bin/whalebrew install quay.io/skopeo/stable:latest
      - run:
          name: "Update homebrew"
          command: |
            eval "$(homebrew/bin/brew shellenv)"
            brew update --quiet || true
            # chmod -R go-w "$(brew --prefix)/share/zsh"
      - run:
          name: "Run test-bot"
          command: | 
            eval "$(homebrew/bin/brew shellenv)"
            brew test-bot --only-formulae --testing-formulae << pipeline.parameters.formula >>
      - run:
          name: "Run pr-upload"
          command: | 
            export HOMEBREW_GITHUB_PACKAGES_USER=mattruzzi
            brew pr-upload --root-url https://ghcr.io/v2/mattruzzi/core
      - run:
          name: "Bottle << pipeline.parameters.formula >>"
          command: |
            eval "$(homebrew/bin/brew shellenv)"
            brew install << pipeline.parameters.formula >> --build-bottle
            brew bottle << pipeline.parameters.formula >>
            mkdir /tmp/bottles
            cp *bottle* /tmp/bottles
      - store_artifacts: 
          path: /tmp/bottles
      - restore_cache:
          keys: 
            - homebrew-with-ghr
      - run:
          name: "Install ghr"
          command: |
            eval "$(homebrew/bin/brew shellenv)"
            brew install ghr
      - save_cache:
          key: homebrew-with-ghr
          paths:
            - homebrew
      - run:
          name: "Release"
          command: |
            eval "$(homebrew/bin/brew shellenv)"
            git clone https://github.com/mattruzzi/bottle-release-test
            cd bottle-release-test
            ghr --token $GITHUB_TOKEN v0.0.0-<< pipeline.parameters.formula >>-$(brew info << pipeline.parameters.formula >> --json | jq -r '.[0].versions.stable') /tmp/bottles/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello

orbs:
  github-release: h-matsuo/github-release@0.1.3
  go: circleci/go@1.7.1
